version: "3"

services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: ./env/flask/Dockerfile-flask
    environment:
      - FLASK_ENV
    restart: always
    ports:
      - "32770:22"
      - "8888:8888" # 測試用，正式環境需刪除
    volumes:
      - ./webapp:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: ./env/nginx/Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mysql:
    image: webapp-mysql
    build:
      context: .
      dockerfile: ./env/mysql/Dockerfile-mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      #      - ./mysql:/var/lib/mysql
      - ./env/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
#      - mysql_data:/var/lib/mysql/data

#volumes:
#  mysql_data:

#networks:
#  hccu:
